version: "3"

services:
  database:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_DB: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
